package TaskOperations.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Deliver = 0;
  public static final int Grasp = 1;
  public static final int Move = 2;
  public static final int TaskDelivery = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xcf635ce519764c6bL, 0xb1c5f43814e251b9L);
    builder.put(0x25c82fc5fc335bf1L, Deliver);
    builder.put(0x25c82fc5fc335befL, Grasp);
    builder.put(0x25c82fc5fc335bf0L, Move);
    builder.put(0x25c82fc5fc335becL, TaskDelivery);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
