package TaskOperations.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptGlobalGoal = createDescriptorForGlobalGoal();
  /*package*/ final ConceptDescriptor myConceptLocalGoal = createDescriptorForLocalGoal();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptGlobalGoal, myConceptLocalGoal);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.GlobalGoal:
        return myConceptGlobalGoal;
      case LanguageConceptSwitch.LocalGoal:
        return myConceptLocalGoal;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForGlobalGoal() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TaskOperations", "GlobalGoal", 0xcf635ce519764c6bL, 0xb1c5f43814e251b9L, 0x51f789b6b56d0fddL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:29f7a628-28dd-48e5-91bd-80e6f08a79f0(TaskOperations.structure)/5906340854140571613");
    b.version(2);
    b.property("description", 0x51f789b6b56d0fe0L).type(PrimitiveTypeId.STRING).origin("5906340854140571616").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLocalGoal() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TaskOperations", "LocalGoal", 0xcf635ce519764c6bL, 0xb1c5f43814e251b9L, 0x51f789b6b56d0fd8L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:29f7a628-28dd-48e5-91bd-80e6f08a79f0(TaskOperations.structure)/5906340854140571608");
    b.version(2);
    b.property("description", 0x51f789b6b56d0fdbL).type(PrimitiveTypeId.STRING).origin("5906340854140571611").done();
    return b.create();
  }
}
