package QoS2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CProfileType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CProfileType() {
    super(0x7dab61f1eec3413dL, 0xb47f81576dbe9733L, 0x7d1b637ab2f72918L, "CProfileType", "r:2d5a0d35-ace0-4319-bd61-7d938c67e595(QoS2.structure)/9014908457751882008");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Traffic_0 = new EnumerationDescriptor.MemberDescriptor("Traffic", "Traffic", 0x7d1b637ab2f72919L, "r:2d5a0d35-ace0-4319-bd61-7d938c67e595(QoS2.structure)/9014908457751882009");
  private final EnumerationDescriptor.MemberDescriptor myMember_Location_0 = new EnumerationDescriptor.MemberDescriptor("Location", "Location", 0x7d1b637ab2f7291aL, "r:2d5a0d35-ace0-4319-bd61-7d938c67e595(QoS2.structure)/9014908457751882010");
  private final EnumerationDescriptor.MemberDescriptor myMember_ObjectDetection_0 = new EnumerationDescriptor.MemberDescriptor("ObjectDetection", "ObjectDetection", 0x7d1b637ab2f7291dL, "r:2d5a0d35-ace0-4319-bd61-7d938c67e595(QoS2.structure)/9014908457751882013");
  private final EnumerationDescriptor.MemberDescriptor myMember_Warnings_0 = new EnumerationDescriptor.MemberDescriptor("Warnings", "Warnings", 0x7d1b637ab2f72921L, "r:2d5a0d35-ace0-4319-bd61-7d938c67e595(QoS2.structure)/9014908457751882017");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7dab61f1eec3413dL, 0xb47f81576dbe9733L, 0x7d1b637ab2f72918L, 0x7d1b637ab2f72919L, 0x7d1b637ab2f7291aL, 0x7d1b637ab2f7291dL, 0x7d1b637ab2f72921L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Traffic_0, myMember_Location_0, myMember_ObjectDetection_0, myMember_Warnings_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Traffic":
        return myMember_Traffic_0;
      case "Location":
        return myMember_Location_0;
      case "ObjectDetection":
        return myMember_ObjectDetection_0;
      case "Warnings":
        return myMember_Warnings_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
