package TaskOperations.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Deliver_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Grasp_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Move_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new TaskDelivery_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xcf635ce519764c6bL, 0xb1c5f43814e251b9L, 0x25c82fc5fc335bf1L), MetaIdFactory.conceptId(0xcf635ce519764c6bL, 0xb1c5f43814e251b9L, 0x25c82fc5fc335befL), MetaIdFactory.conceptId(0xcf635ce519764c6bL, 0xb1c5f43814e251b9L, 0x25c82fc5fc335bf0L), MetaIdFactory.conceptId(0xcf635ce519764c6bL, 0xb1c5f43814e251b9L, 0x25c82fc5fc335becL)).seal();
}
