package NFR.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_OperatorEnumeration extends EnumerationDescriptorBase {

  public EnumerationDescriptor_OperatorEnumeration() {
    super(0xddad85b58f7640d8L, 0x9a0dbd322c713e77L, 0x6a627af554ccd6afL, "OperatorEnumeration", "r:1719899a-db6b-455c-abab-be63243c90ab(NFR.structure)/7665824709846292143");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_greater_than_equal_to_0 = new EnumerationDescriptor.MemberDescriptor("greater_than_equal_to", "greater_than_equal_to", 0x6a627af554ccd6b0L, "r:1719899a-db6b-455c-abab-be63243c90ab(NFR.structure)/7665824709846292144");
  private final EnumerationDescriptor.MemberDescriptor myMember_less_than_equal_to_0 = new EnumerationDescriptor.MemberDescriptor("less_than_equal_to", "less_than_equal_to", 0x6a627af554ccd6b1L, "r:1719899a-db6b-455c-abab-be63243c90ab(NFR.structure)/7665824709846292145");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xddad85b58f7640d8L, 0x9a0dbd322c713e77L, 0x6a627af554ccd6afL, 0x6a627af554ccd6b0L, 0x6a627af554ccd6b1L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_greater_than_equal_to_0, myMember_less_than_equal_to_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "greater_than_equal_to":
        return myMember_greater_than_equal_to_0;
      case "less_than_equal_to":
        return myMember_less_than_equal_to_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
