package NFR.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Performance = 0;
  public static final int QuantifyNFR = 1;
  public static final int Safety = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xddad85b58f7640d8L, 0x9a0dbd322c713e77L);
    builder.put(0x66d5a6d2efc1fb34L, Performance);
    builder.put(0x66d5a6d2efc2c6ebL, QuantifyNFR);
    builder.put(0x66d5a6d2efc2c321L, Safety);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
